Repository Picsart-Academy-UI/ui, pull requests merged in 2021-01, with the labels that each got.

#48 Fetch optimization
  src/hooks/http.js
  src/hooks/useFetch.js
  src/pages/SignIn/helpers/getGoogleRequestData.js
  src/pages/SignIn/index.jsx
  src/store/index.js
  src/store/slices/signinSlice.js
Labels: code review

#47 Optimizing Users and Teams Page and adding 2 actions in Users Page
  src/components/PaginationActions/index.jsx
  src/pages/Teams/components/DeleteRow/index.jsx
  src/pages/Teams/components/EditRow/index.jsx
  src/pages/Teams/components/TeamRow/index.jsx
  src/pages/Users/components/BookaSeat/index.jsx
  src/pages/Users/components/DeleteRow/index.jsx
  src/pages/Users/components/EditRow/index.jsx
  src/pages/Users/components/GoToProfile/index.jsx
  src/pages/Users/components/UserRow/index.jsx
  src/pages/Users/components/UsersTable/index.jsx
Labels: code review

#50 separating request data by page names
  src/constants/index.js
  src/pages/SignIn/index.jsx
  src/pages/UsersCreate/index.jsx
  src/services/signin/getGoogleRequestData.js
  src/services/users/getUserInvitationRequestData.js
Labels: code review

#52 User invite optimization
  src/pages/Users/components/AddUser/index.jsx
  src/pages/UsersCreate/index.jsx
  src/pages/UsersInvite/components/Input.jsx
  src/pages/UsersInvite/components/InputDate.jsx
  src/pages/UsersInvite/index.jsx
  src/pages/UsersInvite/style.js
  src/routes/index.jsx
Labels: code review

#53 teams/create functionality
  src/pages/Teams/components/AddTeam/index.jsx
  src/pages/TeamsCreate/index.jsx
  src/pages/TeamsCreate/style.js
  src/services/teams/addTeamRequest.js
  src/services/teams/getTeamCreateRequestData.js
Labels: code review

#55 Add team select in user invite
  src/pages/SignIn/index.jsx
  src/pages/TeamsCreate/index.jsx
  src/pages/Users/index.jsx
  src/pages/UsersInvite/components/Input.jsx
  src/pages/UsersInvite/components/Input/index.jsx
  src/pages/UsersInvite/components/Input/style.js
  src/pages/UsersInvite/components/InputDate/index.jsx
  src/pages/UsersInvite/components/SelectTeam/index.jsx
  src/pages/UsersInvite/components/SelectTeam/style.js
  src/pages/UsersInvite/index.jsx
  src/pages/UsersInvite/style.js
  src/services/signin/index.js
  src/services/teams/addTeamRequest.js
  src/services/teams/index.js
  src/services/users/getLimitedUsersData.js
  src/services/users/getUserInvitationRequestData.js
  src/services/users/index.js
Labels: code review

#56 changed the profile data from mock to real
  .eslintrc.js
  src/pages/Profile/components/TeamList.jsx
  src/pages/Profile/index.jsx
  src/pages/SignIn/index.jsx
  src/routes/index.jsx
  src/services/profile/getAllTeams.js
  src/store/slices/signinSlice.js
Labels: code review

#59 Pagination fetchs
  src/components/PaginationActions/index.jsx
  src/pages/Users/components/UsersTable/index.jsx
  src/pages/Users/index.jsx
Labels: code review

#61 Change @material UI/core imports style and optimize bundle size in development mode
  .babelrc.js
  .eslintrc.js
  config-overrides.js
  package-lock.json
  package.json
  src/App.jsx
  src/components/Filter/index.jsx
  src/components/Header/index.jsx
  src/components/Pagination/index.jsx
  src/components/PaginationActions/index.jsx
  src/components/SelectDropdown/index.jsx
  src/pages/NotFound/index.jsx
  src/pages/Requests/LinearProgressWithLabel/index.js
  src/pages/Requests/Loads/index.jsx
  src/pages/Requests/RequestsTable/index.jsx
  src/pages/Requests/UserInfo/index.jsx
  src/pages/Reservations/components/CustomTable.jsx
  src/pages/Reservations/index.jsx
  src/pages/SignIn/index.jsx
  src/pages/Teams/components/AddTeam/index.jsx
  src/pages/Teams/components/DeleteRow/index.jsx
  src/pages/Teams/components/EditRow/index.jsx
  src/pages/Teams/components/SearchBox/index.jsx
  src/pages/Teams/components/TeamRow/index.jsx
  src/pages/Teams/components/TeamsTable/index.jsx
  src/pages/TeamsCreate/index.jsx
  src/pages/Users/components/AddUser/index.jsx
  src/pages/Users/components/BookaSeat/index.jsx
  src/pages/Users/components/DeleteRow/index.jsx
  src/pages/Users/components/DropDown/index.jsx
  src/pages/Users/components/EditRow/index.jsx
  src/pages/Users/components/GoToProfile/index.jsx
  src/pages/Users/components/SearchBox/index.jsx
  src/pages/Users/components/UserRow/index.jsx
  src/pages/Users/components/UsersTable/index.jsx
  src/pages/Users/index.jsx
  src/pages/UsersInvite/components/Input/index.jsx
  src/pages/UsersInvite/components/SelectTeam/index.jsx
  src/pages/UsersInvite/index.jsx
Labels: code review

#62 added functions to get data for teams requests
  src/services/teams/index.js
Labels: code review

#63 Add user delete functionality
  src/pages/Users/components/Delete/index.jsx
  src/pages/Users/components/DeleteRow/index.jsx
  src/pages/Users/components/UserRow/index.jsx
  src/services/users/index.js
  src/store/slices/usersSlice.js
Labels: code review

#40 Create reservation create page
  src/pages/Reservations/components/CustomTable.jsx
  src/pages/Reservations/index.jsx
  src/pages/ReservationsCreate/components/Canvas/Canvas.jsx
  src/pages/ReservationsCreate/components/Canvas/style.jsx
  src/pages/ReservationsCreate/index.jsx
  src/pages/ReservationsCreate/styles.jsx
Labels: code review

#64 some small fixes
  .eslintrc.js
  debug.log
  src/components/PaginationActions/index.jsx
  src/pages/Profile/index.jsx
  src/pages/Requests/index.jsx
  src/pages/ReservationsCreate/index.jsx
  src/pages/ReservationsCreate/styles.js
  src/pages/SignIn/text.js
  src/pages/Users/components/GoToProfile/index.jsx
  src/pages/Users/index.jsx
  src/services/profile/getUserById.js
  src/services/teams/index.js
  src/services/users/index.js
Labels: code review

#60 update header position and add users table body scrolling
  src/components/Header/index.jsx
  src/hooks/style/useStylesMain.js
  src/pages/Users/components/AddUser/index.jsx
  src/pages/Users/components/DropDown/index.jsx
  src/pages/Users/components/DropDown/style.js
  src/pages/Users/components/SearchBox/index.jsx
  src/pages/Users/components/UsersTable/index.jsx
  src/pages/Users/components/UsersTable/style.js
  src/pages/Users/index.jsx
Labels: code review

#66 rewriten potentially dangerous lines
  src/pages/Profile/components/TeamList.jsx
  src/pages/Profile/index.jsx
Labels: code review

#67 Del issue
  src/pages/Profile/index.jsx
  src/pages/Users/components/Delete/index.jsx
  src/pages/Users/components/EditRow/index.jsx
  src/pages/Users/components/UserRow/index.jsx
  src/pages/Users/components/UsersTable/index.jsx
  src/pages/Users/index.jsx
  src/store/slices/usersSlice.js
Labels: code review

#68 User ivite validation
  .eslintrc.js
  src/constants/index.js
  src/hooks/style/useStylesMain.js
  src/hooks/useFetch.js
  src/pages/NotFound/index.jsx
  src/pages/NotFound/style.js
  src/pages/SignIn/index.jsx
  src/pages/Users/index.jsx
  src/pages/UsersInvite/components/Alert/index.jsx
  src/pages/UsersInvite/components/Form/helpers/useForm.js
  src/pages/UsersInvite/components/Form/helpers/validateInfo.js
  src/pages/UsersInvite/components/Form/index.jsx
  src/pages/UsersInvite/components/Form/style.js
  src/pages/UsersInvite/components/Input/index.jsx
  src/pages/UsersInvite/components/InputDate/index.jsx
  src/pages/UsersInvite/components/SelectTeam/index.jsx
  src/pages/UsersInvite/components/SnackBar/index.jsx
  src/pages/UsersInvite/index.jsx
  src/store/index.js
  src/store/slices/teamsSlice.js
Labels: code review

#69 add validate separately, picsart logo, change button style
  public/images/picsart.jpg
  src/constants/index.js
  src/hooks/style/useStylesMain.js
  src/hooks/useFetch.js
  src/pages/Profile/components/TeamList.jsx
  src/pages/Profile/index.jsx
  src/pages/Reservations/index.jsx
  src/pages/Reservations/style.js
  src/pages/UsersInvite/components/Form/helpers/useForm.js
  src/pages/UsersInvite/components/SelectTeam/index.jsx
Labels: code review

#70 Get teams in users, updateing users Teams
  src/pages/Users/components/Delete/index.jsx
  src/pages/Users/components/UserRow/index.jsx
  src/pages/Users/components/UsersTable/index.jsx
  src/pages/Users/index.jsx
  src/pages/UsersInvite/components/Form/helpers/useForm.js
  src/pages/UsersInvite/components/SelectTeam/index.jsx
  src/pages/UsersInvite/index.jsx
Labels: code review

#71 User search
  src/pages/Users/components/SearchBox/index.jsx
  src/pages/Users/components/UserRow/index.jsx
  src/pages/Users/components/UsersTable/index.jsx
  src/pages/Users/index.jsx
  src/services/users/index.js
Labels: code review

#73 Add file-folder.md
  LICENSE
  docs/file-folder.md
  public/README.md
  src/README.md
  src/assets/Example/README.md
  src/assets/Fonts/README.md
  src/assets/README.md
  src/components/ExampleComponent/README.md
  src/components/ExampleComponent/index.js
  src/components/README.md
  src/constants/README.md
  src/constants/index.js
  src/hooks/useStylesMain.js
  src/index.jsx
  src/pages/README.md
  src/pages/SignIn/index.jsx
  src/pages/Users/components/UserRow/index.jsx
  src/pages/Users/index.jsx
  src/pages/UsersInvite/components/Form/helpers/useForm.js
  src/pages/UsersInvite/components/Form/helpers/validateInfo.js
  src/pages/UsersInvite/components/Form/index.jsx
  src/pages/UsersInvite/index.jsx
  src/routes/index.jsx
  src/store/README.md
  src/store/index.js
  src/store/slices/README.md
  src/store/slices/TestSlice.js
  src/utils/README.md
Labels: code review

#75 style google button, deletion check modal
  public/images/chairs.jpeg
  public/images/glogo.png
  public/images/google.png
  src/components/AlertDialog/index.jsx
  src/components/AlertDialog/style.js
  src/constants/index.js
  src/hooks/useFetch.js
  src/hooks/useStylesMain.js
  src/pages/SignIn/index.jsx
  src/pages/SignIn/style.js
  src/pages/Teams/components/AddTeam/index.jsx
  src/pages/Teams/components/Search/index.jsx
  src/pages/Teams/components/SearchBox/index.jsx
  src/pages/Teams/index.jsx
  src/pages/Teams/style.js
  src/pages/Users/components/Delete/index.jsx
  src/pages/Users/components/UserRow/index.jsx
  src/pages/UsersInvite/components/Form/helpers/validateInfo.js
Labels: code review

#76 add tables, chairs all API request data
  src/pages/Profile/index.jsx
  src/pages/Users/components/UserRow/index.jsx
  src/pages/UsersInvite/components/Form/helpers/useForm.js
  src/pages/UsersInvite/components/Form/helpers/validateInfo.js
  src/pages/UsersInvite/components/Form/index.jsx
  src/pages/UsersInvite/index.jsx
  src/services/chairs/index.js
  src/services/tables/index.js
Labels: code review

#77 User search debounce
  package-lock.json
  package.json
  src/pages/Users/components/DropDown/index.jsx
  src/pages/Users/components/SearchBox/index.jsx
  src/pages/Users/components/UserRow/index.jsx
  src/pages/Users/components/UsersTable/index.jsx
  src/pages/Users/index.jsx
Labels: code review

#80 Adding filtering functionality By Team on Dropdown in Users Page
  src/pages/Users/components/TeamsDropDown/index.jsx
  src/pages/Users/components/TeamsDropDown/style.js
  src/pages/Users/components/UserRow/index.jsx
  src/pages/Users/index.jsx
  src/services/users/index.js
Labels: code review

#81 UI first basic tests
  .eslintrc.js
  .huskyrc.json
  package-lock.json
  package.json
  src/__mocks__/index.js
  src/__mocks__/slices/profileSlice.js
  src/__mocks__/slices/signinSlice.js
  src/__mocks__/slices/teamsSlice.js
  src/__mocks__/slices/usersSlice.js
  src/components/Filter/tests/filter.test.js
  src/components/Pagination/tests/pagination.test.js
  src/components/PaginationActions/tests/paginationactions.test.js
  src/components/SelectDropdown/tests/selectdropdown.test.js
  src/hooks/useFetch.js
  src/pages/NotFound/tests/index.test.js
  src/pages/Profile/index.jsx
  src/pages/Profile/tests/index.test.js
  src/pages/Requests/tests/load.test.js
  src/pages/Requests/tests/requests.test.js
  src/pages/SignIn/index.jsx
  src/pages/SignIn/tests/index.test.js
  src/pages/Teams/components/AddTeam/tests/index.test.js
  src/pages/Teams/components/TeamsTable/index.jsx
  src/pages/Teams/components/TeamsTable/tests/index.test.js
  src/pages/Users/components/AddUser/tests/adduser.test.js
  src/pages/Users/components/Delete/tests/deleteuser.test.js
  src/pages/Users/components/EditRow/index.jsx
  src/pages/Users/tests/users.test.js
  src/pages/UsersInvite/components/SnackBar/index.jsx
  src/pages/UsersInvite/components/SnackBar/tests/snackbar.test.js
  src/pages/UsersInvite/style.js
  src/setupTests.js
Labels: code review

#82 UI first basic tests
  src/pages/UsersInvite/components/SnackBar/index.jsx
  src/pages/UsersInvite/components/SnackBar/tests/snackbar.test.js
Labels: bug

#78 Real data for teams, deleteTeam functionality, addTeam functionality enhancement
  src/components/SelectDropdown/index.jsx
  src/pages/Profile/components/TeamList.jsx
  src/pages/Teams/components/DeleteRow/index.jsx
  src/pages/Teams/components/TeamRow/index.jsx
  src/pages/Teams/components/TeamsTable/index.jsx
  src/pages/Teams/index.jsx
  src/pages/TeamsCreate/index.jsx
  src/pages/UsersInvite/components/SelectTeam/index.jsx
  src/store/slices/teamsSlice.js
Labels: code review

#86 Delete team issue
  src/hooks/useFetch.js
  src/pages/Teams/components/Delete/index.jsx
  src/pages/Teams/components/TeamRow/index.jsx
  src/pages/TeamsEdit/index.jsx
  src/pages/Users/index.jsx
  src/pages/UsersInvite/components/SelectTeam/index.jsx
Labels: code review

#85 Requests page
  .eslintrc.js
  .huskyrc.json
  package-lock.json
  package.json
  src/components/Filter/index.jsx
  src/components/Header/desktopMenuLeftUtils.js
  src/components/SelectDropdown/index.jsx
  src/hooks/useBatchDispatch.js
  src/hooks/useMemoSelector.js
  src/pages/Requests/Loads/index.jsx
  src/pages/Requests/LoadsDialog/index.jsx
  src/pages/Requests/RequestsTable/index.jsx
  src/pages/Requests/index.jsx
  src/pages/Requests/style.js
  src/services/reservationsService.js
  src/services/teamsService.js
  src/services/usersService.js
  src/store/index.js
  src/store/selectors/index.js
  src/store/slices/reservationsSlice.js
  src/store/slices/teamsSlice.js
  src/utils/helpers.js
  src/utils/makeRequest.js
Labels: code review

#87 Create reservation create page
  .eslintrc.js
  public/images/chairs.jpeg
  src/components/Header/desktopMenuLeftUtils.js
  src/constants/index.js
  src/pages/Reservations/index.jsx
  src/pages/ReservationsCreate/components/Canvas/Canvas.jsx
  src/pages/ReservationsCreate/components/Canvas/style.jsx
  src/pages/ReservationsCreate/components/Loader/index.jsx
  src/pages/ReservationsCreate/components/Loader/style.js
  src/pages/ReservationsCreate/components/Pickers/index.jsx
  src/pages/ReservationsCreate/components/Pickers/style.js
  src/pages/ReservationsCreate/components/Receipt/index.jsx
  src/pages/ReservationsCreate/components/Receipt/style.js
  src/pages/ReservationsCreate/components/TableOfTables/index.jsx
  src/pages/ReservationsCreate/components/TableOfTables/style.js
  src/pages/ReservationsCreate/index.jsx
  src/pages/ReservationsCreate/style.js
  src/pages/SignIn/index.jsx
  src/pages/TeamsCreate/index.jsx
  src/services/profile/getUserById.js
  src/services/reservationsService.js
  src/services/teamsService.js
  src/services/usersService.js
  src/store/selectors/index.js
Labels: code review

#89 Users in UserMode, adding Search by name for User
  src/hooks/useMountedRef.js
  src/pages/Users/components/Delete/index.jsx
  src/pages/Users/components/UserRow/index.jsx
  src/pages/Users/components/UsersTable/index.jsx
  src/pages/Users/components/UsersTable/style.js
  src/pages/Users/index.jsx
  src/services/users/index.js
  src/store/slices/usersSlice.js
Labels: code review

#98 UI profile edit teams issue
  src/pages/Profile/index.jsx
  src/store/slices/signinSlice.js
Labels: code review

#101 add avatar, add loader, refactor some styles
  src/components/Header/index.jsx
  src/components/Header/style.js
  src/components/Header/utils.js
  src/constants/index.js
  src/hooks/useStylesMain.js
  src/pages/Profile/helpers/updateUser.js
  src/pages/Requests/RequestsTable/index.jsx
  src/pages/Reservations/components/CustomTable.jsx
  src/pages/SignIn/index.jsx
  src/pages/Users/components/UsersTable/index.jsx
  src/pages/UsersInvite/components/Form/index.jsx
  src/pages/UsersInvite/index.jsx
  src/services/profile/updateUser.js
  src/services/signinService.js
  src/services/users/index.js
Labels: code review

#104 userinvite restyling for different screen sizes
  src/hooks/useStylesMain.js
  src/pages/UsersInvite/components/Form/index.jsx
  src/pages/UsersInvite/components/Form/style.js
  src/pages/UsersInvite/index.jsx
Labels: code review

#105 Refactor users, some fixing
  src/components/Header/index.jsx
  src/constants/index.js
  src/hooks/useDebounce.js
  src/pages/Users/components/Delete/index.jsx
  src/pages/Users/components/SearchBox/index.jsx
  src/pages/Users/components/TeamsDropDown/index.jsx
  src/pages/Users/components/UserRow/index.jsx
  src/pages/Users/components/UsersTable/index.jsx
  src/pages/Users/index.jsx
  src/pages/Users/style.js
  src/pages/UsersEdit/index.jsx
  src/routes/index.jsx
Labels: code review

#109 add env
  .env
  .env.development
  .env.production
  .gitignore
Labels: code review

#112 Fix env & delete unused packages
  .env
  .env.development
  .env.production
  .gitignore
  README.md
  env
  env.development
  env.production
  package-lock.json
  package.json
Labels: code review

#113 teams fetch reversing to the working state
  src/pages/Teams/index.jsx
Labels: bug, code review

#117 Users Page loading fix
  src/pages/Users/components/UsersTable/index.jsx
  src/pages/Users/index.jsx
Labels: code review

#118 delete unused files in Users Components
  src/pages/Users/components/SearchBox/index.jsx
  src/pages/Users/components/TeamsDropDown/index.jsx
  src/pages/Users/components/TeamsDropDown/style.js
Labels: code review
