Repository Picsart-Academy-UI/ui, pull requests merged in 2021-02, with the labels that each got.

#122 change signin page style, snackbar positon
  public/fonts.css
  public/images/background.jpg
  public/images/chair.png
  src/constants/index.js
  src/hooks/useStylesMain.js
  src/pages/SignIn/index.jsx
  src/pages/SignIn/style.js
  src/pages/UsersInvite/components/Form/index.jsx
  src/pages/UsersInvite/components/SnackBar/index.jsx
Labels: code review

#121 Push notifications
  .eslintrc.js
  public/sw.js
  src/App.jsx
  src/components/Header/index.jsx
  src/constants/index.js
  src/services/registerSW.js
  src/services/signinService.js
  src/services/subscribePush.js
  src/services/urlBase64ToUint8Array.js
  src/store/slices/signinSlice.js
Labels: code review

#99 added SeeTeamTables UI, functionality, CreateTable functionality, DeleteTable functionality
  src/components/Header/index.jsx
  src/components/Header/utils.js
  src/constants/index.js
  src/pages/SignIn/index.jsx
  src/pages/Tables/components/AddTable/index.jsx
  src/pages/Tables/components/DeleteRow/index.jsx
  src/pages/Tables/components/EditRow/index.jsx
  src/pages/Tables/components/TeamTableRow/index.jsx
  src/pages/Tables/index.jsx
  src/pages/Tables/style.js
  src/pages/TablesCreate/index.jsx
  src/pages/Teams/components/SeeTeamTables/index.jsx
  src/pages/Teams/components/TeamRow/index.jsx
  src/routes/index.jsx
  src/services/reservationsService.js
  src/store/index.js
  src/store/slices/chairsSlice.js
  src/store/slices/reservationsSlice.js
  src/store/slices/tablesSlice.js
  ․env
  ․env.development
  ․env.production
Labels: code review

#124 Fix tables
  src/pages/Tables/index.jsx
  src/services/chairs/index.js
  src/services/tables/index.js
Labels: code review

#128 Fixings in the all app
  .env
  README.md
  src/components/TablePageWrapper/index.jsx
  src/constants/index.js
  src/hooks/useFetch.js
  src/hooks/useStylesMain.js
  src/pages/Profile/components/TeamList.jsx
  src/pages/Profile/helpers/updateUser.js
  src/pages/Profile/index.jsx
  src/pages/Requests/LoadsDialog/index.jsx
  src/pages/Requests/index.jsx
  src/pages/Reservations/index.jsx
  src/pages/ReservationsCreate/components/ChairTableRow/index.jsx
  src/pages/ReservationsCreate/components/Receipt/index.jsx
  src/pages/ReservationsCreate/components/TableOfTables/index.jsx
  src/pages/SignIn/index.jsx
  src/pages/Tables/components/Add/index.jsx
  src/pages/Tables/components/Delete/index.jsx
  src/pages/Tables/components/Edit/index.jsx
  src/pages/Tables/components/TableListRow/index.jsx
  src/pages/Tables/index.jsx
  src/pages/Tables/style.js
  src/pages/TablesCreate/index.jsx
  src/pages/Teams/components/Delete/index.jsx
  src/pages/Teams/components/Edit/index.jsx
  src/pages/Teams/components/TeamRow/index.jsx
  src/pages/Teams/components/TeamTable/index.jsx
  src/pages/Teams/components/TeamsTable/index.jsx
  src/pages/Teams/index.jsx
  src/pages/TeamsCreate/index.jsx
  src/pages/TeamsEdit/index.jsx
  src/pages/Users/components/Delete/index.jsx
  src/pages/Users/components/Delete/tests/deleteuser.test.js
  src/pages/Users/index.jsx
  src/pages/UsersInvite/components/Input/index.jsx
  src/pages/UsersInvite/components/Input/style.js
  src/pages/UsersInvite/components/SelectTeam/index.jsx
  src/pages/UsersInvite/components/SelectTeam/style.js
  src/pages/UsersInvite/index.jsx
  src/routes/index.jsx
  src/services/authService.js
  src/services/index.js
  src/services/reservationsService.js
  src/services/signinService.js
  src/services/tables/index.js
  src/services/tablesService.js
  src/services/teams/index.js
  src/services/teamsService.js
  src/services/users/index.js
  src/services/usersService.js
  src/services/utils.js
  src/store/slices/reservationsSlice.js
  src/store/slices/signinSlice.js
  src/store/slices/tablesSlice.js
  src/store/slices/teamsSlice.js
  src/utils/makeRequest.js
  ․env.development
Labels: bug, code review, good first issue, style

#131 Fixing in users(Loading, some search and SelectTeam issues with Pagination)
  .huskyrc.json
  src/hooks/useMount.js
  src/pages/Users/components/DeleteUser/index.jsx
  src/pages/Users/components/DeleteUser/tests/deleteuser.test.js
  src/pages/Users/components/GoToReservations/index.jsx
  src/pages/Users/components/UserRow/index.jsx
  src/pages/Users/components/UsersTable/index.jsx
  src/pages/Users/index.jsx
  src/routes/index.jsx
  src/store/slices/usersSlice.js
Labels: code review

#136 small fixes
  package.json
  src/__mocks__/index.js
  src/components/ButtonLoading/index.jsx
  src/components/Header/index.jsx
  src/components/Pagination/index.jsx
  src/components/PaginationActions/index.jsx
  src/pages/NotFound/style.js
  src/pages/Profile/hooks/useUpdateUserHook.js
  src/pages/Profile/index.jsx
  src/pages/Requests/RequestsTable/index.jsx
  src/pages/Requests/RequestsTable/style.js
  src/pages/Reservations/components/ResTable/index.jsx
  src/pages/Tables/components/Delete/index.jsx
  src/pages/Users/index.jsx
Labels: code review

#137 add phone number package and validation
  package-lock.json
  package.json
  src/components/TeamsDropdown/index.jsx
  src/hooks/useStylesMain.js
  src/pages/Profile/index.jsx
  src/pages/TablesCreate/components/Form/index.jsx
  src/pages/TablesCreate/components/Form/utils/validateInfo.js
  src/pages/UsersInvite/components/Form/helpers/useForm.js
  src/pages/UsersInvite/components/Form/hooks/useForm.js
  src/pages/UsersInvite/components/Form/index.jsx
  src/pages/UsersInvite/components/InputPhone/index.jsx
  src/pages/UsersInvite/index.jsx
  src/utils/validateInfo.js
Labels: code review

#139 Moving state from local to Redux
  src/pages/Users/index.jsx
  src/store/slices/usersSlice.js
Labels: code review

#140 Fixing Material warnings in Users Page
  src/pages/Users/index.jsx
Labels: code review

#142 Fix table infinity fetch when no tables
  src/pages/Tables/index.jsx
Labels: bug, code review
